import { W,H } from './constants.js';
import { S } from './state.js';
import { rendererCapabilities, effectiveQuality } from '../rendering/capabilities.js';
import { mobilitySnapshot } from '../simulation/mobility.js';
import { recreationSnapshot } from '../simulation/recreation.js';
const enabled=(()=>{try{return new URLSearchParams(location.search).get('debug')==='1';}catch(e){return false;}})();
S.diagnostics.enabled=enabled;
let el=null,frames=0,lastPaint=performance.now(),lastFrame=performance.now();
if(enabled){ el=document.createElement('pre'); el.setAttribute('aria-label','Meadowline developer diagnostics'); el.style.cssText='position:fixed;left:8px;top:8px;z-index:9999;margin:0;padding:8px 10px;max-width:270px;pointer-events:none;background:rgba(18,28,31,.78);color:#eef4e9;border:1px solid rgba(255,255,255,.18);border-radius:8px;font:11px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap'; document.body.appendChild(el); }
export function diagnosticFrameStart(now){ if(!enabled)return; const d=Math.max(0,now-lastFrame);lastFrame=now;S.diagnostics.frameMs=d;frames++;if(now-lastPaint>=1000){S.diagnostics.fps=Math.round(frames*1000/(now-lastPaint));frames=0;lastPaint=now;paintDiagnostics();}}
export function recordSimulationMs(ms){if(enabled)S.diagnostics.simMs=ms;} export function recordRenderMs(ms){if(enabled)S.diagnostics.renderMs=ms;}
export function paintDiagnostics(){
  if(!enabled||!el)return;
  const svc=S.services?.education; const providers=svc?Object.keys(svc.providers||{}).length:0;
  const halls=(S.grid||[]).filter(b=>b?.type==='cityHall'); const hall=halls[0];
  const houses=S.ctx?.houses||[]; const occupied=houses.filter(h=>(h.pop||0)>0).length;
  const avgEdu=houses.length?Math.round(houses.reduce((n,h)=>n+(Number(h.state?.education)||0),0)/houses.length):0;
  const avgDes=houses.length?Math.round(houses.reduce((n,h)=>n+(Number(h.state?.desirability)||0),0)/houses.length):0;
  const mob=mobilitySnapshot(),rec=recreationSnapshot(),caps=rendererCapabilities();
  el.textContent=['MEADOWLINE DEBUG','FPS             '+(S.diagnostics.fps||0),'Frame ms        '+(S.diagnostics.frameMs||0).toFixed(1),'Simulation ms   '+(S.diagnostics.simMs||0).toFixed(2),'Render ms       '+(S.diagnostics.renderMs||0).toFixed(2),'Grid            '+W+'×'+H,'Citizens        '+S.citizens.length,'Vehicles        '+mob.vehicles,'Road tiles      '+mob.roadTiles,'Road components '+mob.components,'Rail crossings  '+mob.crossings,'Active routes   '+mob.activeRoutes,'Route searches  '+(S.diagnostics.vehicleRouteSearches||0),'Route failures  '+(S.diagnostics.vehicleRouteFailures||0),'Vehicle reroutes '+(S.diagnostics.vehicleReroutes||0),'Vehicle despawns '+(S.diagnostics.vehicleDespawns||0),'Wait at rail    '+(S.diagnostics.vehiclesWaitingAtRail||0),'Road invalid.   '+(S.diagnostics.roadNetworkInvalidations||0),'Trains / boats  '+S.trains.length+' / '+S.boats.length,'Edu providers   '+providers,'Service rebuild '+(S.services.recomputes||0),'Rec facilities  '+rec.facilities,'Rec capacity    '+rec.capacity,'Rec demand      '+rec.demand,'Rec served      '+rec.served,'Rec underserved '+rec.underserved,'Rec visitors    '+rec.activeVisitors,'Rec rebuilds    '+(S.diagnostics.recreationRecomputes||0),'Rec route tries '+(S.diagnostics.recreationRouteSearches||0),'Rec route fail  '+(S.diagnostics.recreationRouteFailures||0),'Multi facilities '+(S.diagnostics.multiTileFacilities||0),'Facility tiles  '+(S.diagnostics.occupiedFacilityTiles||0),'Facility repairs '+(S.diagnostics.invalidFacilityCleanup||0),'City stage      '+(S.cityProgress?.stage||0),'Parcels open    '+(S.cityProgress?.unlockedParcels?.length||0),'City Hall count '+halls.length,'City Hall level '+(hall?.state?.level||0),'Occupied homes  '+occupied,'Avg education   '+avgEdu,'Avg desirability '+avgDes,'Summary rebuild '+(S.diagnostics.citySummaryRecomputes||0),'Summary invalid '+(S.diagnostics.citySummaryInvalidations||0),'Hall panel open '+(S.diagnostics.cityHallPanelOpens||0),'Primary goal    '+(S.diagnostics.primaryGoal||'—'),'Optional goal   '+(S.diagnostics.optionalGoal||'—'),'Goal recompute  '+(S.diagnostics.goalRecomputes||0),'Goal replace    '+(S.diagnostics.goalReplacements||0),'Input state     '+(S.diagnostics.inputState||'IDLE'),'Touch pans      '+(S.diagnostics.touchPans||0),'Tap placements  '+(S.diagnostics.tapPlacements||0),'Paint starts    '+(S.diagnostics.paintActivations||0),'Cancel drag     '+(S.diagnostics.cancelledBuildByDrag||0),'Cancel pinch    '+(S.diagnostics.cancelledBuildByPinch||0),'Housing evals   '+(S.diagnostics.housingEvaluations||0),'Housing upgrades '+(S.diagnostics.housingUpgrades||0),'Path searches   '+(S.diagnostics.pathSearches||0),'Save bytes      '+(S.diagnostics.saveBytes||0)].join('\n');
}
